services:
  devcontainer:
    image: "${DEVCONTAINER_IAMGE:-devcontainer:latest}"
    hostname: "devcontainer"
    container_name: "${COMPOSE_PROJECT_NAME}-devcontainer"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./devcontainer
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: devcontainer_hostkey
        target: /etc/ssh/hostkey
      - type: volume
        source: devcontainer_vscode
        target: "${BUILD_USER_HOME:-/home/admin}/.vscode-server"
      - type: volume
        source: devcontainer_local
        target: "${BUILD_USER_HOME:-/home/admin}/.local"
      - type: volume
        source: devcontainer_nvm_nodejs
        target: "${BUILD_USER_HOME:-/home/admin}/.nvm/versions/"
      - type: volume
        source: devcontainer_g_golang
        target: "${BUILD_USER_HOME:-/home/admin}/.g/versions/"
      - type: volume
        source: devcontainer_opencode
        target: "${BUILD_USER_HOME:-/home/admin}/.config/opencode"


  openclaw:
    image: "${OPENCLAW_IAMGE:-openclaw:latest}"
    hostname: "openclaw"
    container_name: "${COMPOSE_PROJECT_NAME}-openclaw"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./openclaw
      dockerfile: Dockerfile
      args:
        DEVCONTAINER_IAMGE: "${DEVCONTAINER_IAMGE:-devcontainer:latest}"
    ports:
      - 18789:18789
      - 18791:18791
    volumes:
      - type: volume
        source: openclaw_workspace
        target: "${BUILD_AGENT_USER_HOME:-/home/agent}/.openclaw/workspace"

  ollama:
    image: ollama/ollama
    hostname: "ollama"
    container_name: "${COMPOSE_PROJECT_NAME}-ollama"
    environment:
      OLLAMA_NUM_CTX: 32000
      OLLAMA_FLASH_ATTENTION: 1
      OLLAMA_KV_CACHE_TYPE: q8_0
      OLLAMA_KEEP_ALIVE: 1h
    ports:
      - 11434:11434
    volumes:
      - type: volume
        source: ollama_data
        target: "/root/.ollama"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge

volumes:
  devcontainer_hostkey:
  devcontainer_vscode:
  devcontainer_local:
  devcontainer_nvm_nodejs:
  devcontainer_g_golang:
  devcontainer_opencode:
  openclaw_workspace:
  ollama_data:
